# .github/workflows/hello.yml
name: Hello CI/CD

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello ${{ secrets.MY_WORD }}"
